function handleClear(req, res) {
  res.statusCode = 200
  res.setHeader('Content-Type', 'text/html')
  res.write('<html>')
  res.write('<head>')
  res.write('<title>Clear Confirmation</title>')
  res.write('<script>')
  res.write('function confirmClear() {')
  res.write('  var confirmed = confirm("Are you sure you want to clear all records?");')
  res.write('  if (confirmed) {')
  res.write('    window.location.href = "/clearConfirmed";')
  res.write('  } else {')
  res.write('    window.location.href = "/";')
  res.write('  }')
  res.write('}')
  res.write('</script>')
  res.write('</head>')
  res.write('<body>')
  res.write('<h1>Clear Confirmation</h1>')
  res.write('<button onclick="confirmClear()">Clear</button>')
  res.write('<button onclick="returnToHomepage()">Return to Homepage</button>')
  res.write('<script>')
  res.write('function returnToHomepage() {')
  res.write('  window.location.href = "/";')
  res.write('}')
  res.write('</script>')
  res.write('</body>')
  res.write('</html>')
  res.end()
}
